export const Mainnet = {
  mode: "dev",
  binanceProvider:
    //'https://be51-122-166-214-23.ngrok-free.app',
    // 'https://binance.llamarpc.com',
    //calvin change
    "https://bsc-dataseed1.binance.org/",

  diamURL: "https://mainnet.diamcircle.io/",
  tokenPrice: "https://min-api.cryptocompare.com",
  ethereumprovider:
    //'https://b71c-122-166-214-23.ngrok-free.app',
    "https://mainnet.infura.io/v3/3bd06d9918e04b1bb4925fe6ab1faa5c",
  binanceContractURL:
    "https://api.bscscan.com/api?module=contract&action=getabi&address=",
  ethereumContractURL:
    "https://api.etherscan.io/api?module=contract&action=getabi&address=",
  binanceAPIKey: "I847DVVEBXNEMJZMQD4BCIUS5AH8HD55JS",
  DIAMNetKey: "Diamante MainNet; SEP 2022",
  etherumAPIKey: "N12JZ89VUK9B471DFMA78XKU95IZME7UBK",
  binanceTransaction: "https://api.bscscan.com/api?module=account&",
  ethereumTransaction: "https://api.etherscan.io/api?module=account&",
  BSCexplorer: "https://bscscan.com/",
  ETHexplorer: "https://etherscan.io/",
  DIAMexplorer: "https://explorer.diamante.io/",
  TronExplorer: "https://tronscan.org/#/",
  TronProvider: "",
  gameDispense: "https://cryptnewsapi.diamcircle.io",
  //calvin change 28/11/23
  TronApiKey: "6cfc63a0-ecfc-47df-ad07-9547701ca289",
  TronContractURL: "",
  TronTransaction: "https://api.trongrid.io/v1/accounts/",
  tronAPI: "https://api.trongrid.io",
  diamWalletURL: "https://dwprodapi.diamcircle.io/",
  commonService: "https://diamjvmapi.diamcircle.io/admin",
  poolWalletAddress: "GB7NKHRWAZ5CYW3AWS25H7FMFRJVR6I7FKMWDO4QVGU4BNCWJVGKT4NV",
  playStoreURL:
    "https://play.google.com/store/apps/details?id=com.diamante.diamwallet&hl=en_IN",
  AppStoreURL: "https://apps.apple.com/in/app/diam-wallet/id6450691849",
  // abi: [
  //   {
  //     asset: "DIAM",
  //     network: 0,
  //     abi: "",
  //     address: "",
  //     decimals: 18,
  //     image: {
  //       src: require("../../assets/images/DIAM.png"),
  //       label: "image",
  //     },
  //   },
  //   {
  //     asset: "DIAM (ERC20)",
  //     network: 2,
  //     abi: [
  //       { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  //       { inputs: [], name: "InvalidShortString", type: "error" },
  //       {
  //         inputs: [{ internalType: "string", name: "str", type: "string" }],
  //         name: "StringTooLong",
  //         type: "error",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "owner",
  //             type: "address",
  //           },
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "spender",
  //             type: "address",
  //           },
  //           {
  //             indexed: false,
  //             internalType: "uint256",
  //             name: "value",
  //             type: "uint256",
  //           },
  //         ],
  //         name: "Approval",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [],
  //         name: "EIP712DomainChanged",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "previousOwner",
  //             type: "address",
  //           },
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "newOwner",
  //             type: "address",
  //           },
  //         ],
  //         name: "OwnershipTransferred",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "from",
  //             type: "address",
  //           },
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "to",
  //             type: "address",
  //           },
  //           {
  //             indexed: false,
  //             internalType: "uint256",
  //             name: "value",
  //             type: "uint256",
  //           },
  //         ],
  //         name: "Transfer",
  //         type: "event",
  //       },
  //       {
  //         inputs: [],
  //         name: "DOMAIN_SEPARATOR",
  //         outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "owner", type: "address" },
  //           { internalType: "address", name: "spender", type: "address" },
  //         ],
  //         name: "allowance",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "spender", type: "address" },
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "approve",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "account", type: "address" },
  //         ],
  //         name: "balanceOf",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "burn",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "decimals",
  //         outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "spender", type: "address" },
  //           {
  //             internalType: "uint256",
  //             name: "subtractedValue",
  //             type: "uint256",
  //           },
  //         ],
  //         name: "decreaseAllowance",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "eip712Domain",
  //         outputs: [
  //           { internalType: "bytes1", name: "fields", type: "bytes1" },
  //           { internalType: "string", name: "name", type: "string" },
  //           { internalType: "string", name: "version", type: "string" },
  //           { internalType: "uint256", name: "chainId", type: "uint256" },
  //           {
  //             internalType: "address",
  //             name: "verifyingContract",
  //             type: "address",
  //           },
  //           { internalType: "bytes32", name: "salt", type: "bytes32" },
  //           {
  //             internalType: "uint256[]",
  //             name: "extensions",
  //             type: "uint256[]",
  //           },
  //         ],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "spender", type: "address" },
  //           { internalType: "uint256", name: "addedValue", type: "uint256" },
  //         ],
  //         name: "increaseAllowance",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //           { internalType: "bytes32", name: "_hash", type: "bytes32" },
  //           { internalType: "uint8", name: "_v", type: "uint8" },
  //           { internalType: "bytes32", name: "_r", type: "bytes32" },
  //           { internalType: "bytes32", name: "_s", type: "bytes32" },
  //           { internalType: "uint256", name: "deadline", type: "uint256" },
  //         ],
  //         name: "mint",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "name",
  //         outputs: [{ internalType: "string", name: "", type: "string" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [{ internalType: "address", name: "owner", type: "address" }],
  //         name: "nonces",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "owner",
  //         outputs: [{ internalType: "address", name: "", type: "address" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "ownerNounce",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "owner", type: "address" },
  //           { internalType: "address", name: "spender", type: "address" },
  //           { internalType: "uint256", name: "value", type: "uint256" },
  //           { internalType: "uint256", name: "deadline", type: "uint256" },
  //           { internalType: "uint8", name: "v", type: "uint8" },
  //           { internalType: "bytes32", name: "r", type: "bytes32" },
  //           { internalType: "bytes32", name: "s", type: "bytes32" },
  //         ],
  //         name: "permit",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "renounceOwnership",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "symbol",
  //         outputs: [{ internalType: "string", name: "", type: "string" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "totalSupply",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "to", type: "address" },
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "transfer",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "from", type: "address" },
  //           { internalType: "address", name: "to", type: "address" },
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "transferFrom",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "newOwner", type: "address" },
  //         ],
  //         name: "transferOwnership",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //     ],
  //     address: "0xcFc05eE86a719A0f8EAfe92175aE1415e7D81277",
  //     decimals: 18,
  //     image: {
  //       src: require("../../assets/images/DIAM.png"),
  //       label: "image",
  //     },
  //   },
  //   {
  //     asset: "DIAM (BEP20)",
  //     network: 1,
  //     abi: [
  //       { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  //       { inputs: [], name: "InvalidShortString", type: "error" },
  //       {
  //         inputs: [{ internalType: "string", name: "str", type: "string" }],
  //         name: "StringTooLong",
  //         type: "error",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "owner",
  //             type: "address",
  //           },
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "spender",
  //             type: "address",
  //           },
  //           {
  //             indexed: false,
  //             internalType: "uint256",
  //             name: "value",
  //             type: "uint256",
  //           },
  //         ],
  //         name: "Approval",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [],
  //         name: "EIP712DomainChanged",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "previousOwner",
  //             type: "address",
  //           },
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "newOwner",
  //             type: "address",
  //           },
  //         ],
  //         name: "OwnershipTransferred",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "from",
  //             type: "address",
  //           },
  //           {
  //             indexed: true,
  //             internalType: "address",
  //             name: "to",
  //             type: "address",
  //           },
  //           {
  //             indexed: false,
  //             internalType: "uint256",
  //             name: "value",
  //             type: "uint256",
  //           },
  //         ],
  //         name: "Transfer",
  //         type: "event",
  //       },
  //       {
  //         inputs: [],
  //         name: "DOMAIN_SEPARATOR",
  //         outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "owner", type: "address" },
  //           { internalType: "address", name: "spender", type: "address" },
  //         ],
  //         name: "allowance",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "spender", type: "address" },
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "approve",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "account", type: "address" },
  //         ],
  //         name: "balanceOf",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "burn",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "decimals",
  //         outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "spender", type: "address" },
  //           {
  //             internalType: "uint256",
  //             name: "subtractedValue",
  //             type: "uint256",
  //           },
  //         ],
  //         name: "decreaseAllowance",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "eip712Domain",
  //         outputs: [
  //           { internalType: "bytes1", name: "fields", type: "bytes1" },
  //           { internalType: "string", name: "name", type: "string" },
  //           { internalType: "string", name: "version", type: "string" },
  //           { internalType: "uint256", name: "chainId", type: "uint256" },
  //           {
  //             internalType: "address",
  //             name: "verifyingContract",
  //             type: "address",
  //           },
  //           { internalType: "bytes32", name: "salt", type: "bytes32" },
  //           {
  //             internalType: "uint256[]",
  //             name: "extensions",
  //             type: "uint256[]",
  //           },
  //         ],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "spender", type: "address" },
  //           { internalType: "uint256", name: "addedValue", type: "uint256" },
  //         ],
  //         name: "increaseAllowance",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //           { internalType: "bytes32", name: "_hash", type: "bytes32" },
  //           { internalType: "uint8", name: "_v", type: "uint8" },
  //           { internalType: "bytes32", name: "_r", type: "bytes32" },
  //           { internalType: "bytes32", name: "_s", type: "bytes32" },
  //           { internalType: "uint256", name: "deadline", type: "uint256" },
  //         ],
  //         name: "mint",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "name",
  //         outputs: [{ internalType: "string", name: "", type: "string" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [{ internalType: "address", name: "owner", type: "address" }],
  //         name: "nonces",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "owner",
  //         outputs: [{ internalType: "address", name: "", type: "address" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "ownerNounce",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "owner", type: "address" },
  //           { internalType: "address", name: "spender", type: "address" },
  //           { internalType: "uint256", name: "value", type: "uint256" },
  //           { internalType: "uint256", name: "deadline", type: "uint256" },
  //           { internalType: "uint8", name: "v", type: "uint8" },
  //           { internalType: "bytes32", name: "r", type: "bytes32" },
  //           { internalType: "bytes32", name: "s", type: "bytes32" },
  //         ],
  //         name: "permit",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "renounceOwnership",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "symbol",
  //         outputs: [{ internalType: "string", name: "", type: "string" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [],
  //         name: "totalSupply",
  //         outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "to", type: "address" },
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "transfer",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "from", type: "address" },
  //           { internalType: "address", name: "to", type: "address" },
  //           { internalType: "uint256", name: "amount", type: "uint256" },
  //         ],
  //         name: "transferFrom",
  //         outputs: [{ internalType: "bool", name: "", type: "bool" }],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         inputs: [
  //           { internalType: "address", name: "newOwner", type: "address" },
  //         ],
  //         name: "transferOwnership",
  //         outputs: [],
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //     ],

  //     address: "0x1FA0f5ed24a1a2b43741E88F8FEc19633e67082B",
  //     decimals: 18,
  //     image: {
  //       src: require("../../assets/images/DIAM.png"),
  //       label: "image",
  //     },
  //   },
  //   {
  //     asset: "ETH",
  //     network: 2,
  //     abi: [
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "name",
  //         outputs: [{ name: "", type: "string" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [
  //           { name: "guy", type: "address" },
  //           { name: "wad", type: "uint256" },
  //         ],
  //         name: "approve",
  //         outputs: [{ name: "", type: "bool" }],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "totalSupply",
  //         outputs: [{ name: "", type: "uint256" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [
  //           { name: "src", type: "address" },
  //           { name: "dst", type: "address" },
  //           { name: "wad", type: "uint256" },
  //         ],
  //         name: "transferFrom",
  //         outputs: [{ name: "", type: "bool" }],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [{ name: "wad", type: "uint256" }],
  //         name: "withdraw",
  //         outputs: [],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "decimals",
  //         outputs: [{ name: "", type: "uint8" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [{ name: "", type: "address" }],
  //         name: "balanceOf",
  //         outputs: [{ name: "", type: "uint256" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "symbol",
  //         outputs: [{ name: "", type: "string" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [
  //           { name: "dst", type: "address" },
  //           { name: "wad", type: "uint256" },
  //         ],
  //         name: "transfer",
  //         outputs: [{ name: "", type: "bool" }],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [],
  //         name: "deposit",
  //         outputs: [],
  //         payable: true,
  //         stateMutability: "payable",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [
  //           { name: "", type: "address" },
  //           { name: "", type: "address" },
  //         ],
  //         name: "allowance",
  //         outputs: [{ name: "", type: "uint256" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       { payable: true, stateMutability: "payable", type: "fallback" },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "src", type: "address" },
  //           { indexed: true, name: "guy", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Approval",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "src", type: "address" },
  //           { indexed: true, name: "dst", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Transfer",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "dst", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Deposit",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "src", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Withdrawal",
  //         type: "event",
  //       },
  //     ],
  //     address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  //     native: true,
  //     decimals: 18,
  //     image: {
  //       src: require("../../assets/images/eth.png"),
  //       label: "image",
  //     },
  //   },
  //   {
  //     asset: "BNB",
  //     network: 1,
  //     native: true,

  //     abi: [
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "name",
  //         outputs: [{ name: "", type: "string" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [
  //           { name: "guy", type: "address" },
  //           { name: "wad", type: "uint256" },
  //         ],
  //         name: "approve",
  //         outputs: [{ name: "", type: "bool" }],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "totalSupply",
  //         outputs: [{ name: "", type: "uint256" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [
  //           { name: "src", type: "address" },
  //           { name: "dst", type: "address" },
  //           { name: "wad", type: "uint256" },
  //         ],
  //         name: "transferFrom",
  //         outputs: [{ name: "", type: "bool" }],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [{ name: "wad", type: "uint256" }],
  //         name: "withdraw",
  //         outputs: [],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "decimals",
  //         outputs: [{ name: "", type: "uint8" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [{ name: "", type: "address" }],
  //         name: "balanceOf",
  //         outputs: [{ name: "", type: "uint256" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [],
  //         name: "symbol",
  //         outputs: [{ name: "", type: "string" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [
  //           { name: "dst", type: "address" },
  //           { name: "wad", type: "uint256" },
  //         ],
  //         name: "transfer",
  //         outputs: [{ name: "", type: "bool" }],
  //         payable: false,
  //         stateMutability: "nonpayable",
  //         type: "function",
  //       },
  //       {
  //         constant: false,
  //         inputs: [],
  //         name: "deposit",
  //         outputs: [],
  //         payable: true,
  //         stateMutability: "payable",
  //         type: "function",
  //       },
  //       {
  //         constant: true,
  //         inputs: [
  //           { name: "", type: "address" },
  //           { name: "", type: "address" },
  //         ],
  //         name: "allowance",
  //         outputs: [{ name: "", type: "uint256" }],
  //         payable: false,
  //         stateMutability: "view",
  //         type: "function",
  //       },
  //       { payable: true, stateMutability: "payable", type: "fallback" },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "src", type: "address" },
  //           { indexed: true, name: "guy", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Approval",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "src", type: "address" },
  //           { indexed: true, name: "dst", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Transfer",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "dst", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Deposit",
  //         type: "event",
  //       },
  //       {
  //         anonymous: false,
  //         inputs: [
  //           { indexed: true, name: "src", type: "address" },
  //           { indexed: false, name: "wad", type: "uint256" },
  //         ],
  //         name: "Withdrawal",
  //         type: "event",
  //       },
  //     ],
  //     address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
  //     decimals: 18,
  //     image: {
  //       src: require("../../assets/images/bnb.png"),
  //       label: "image",
  //     },
  //   },
  //   {
  //     asset: "TRX",
  //     network: 3,
  //     native: true,

  //     abi: "",
  //     address: "TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR",

  //     decimals: 6,
  //     image: {
  //       src: require("../../assets/images/trx.png"),
  //       label: "image",
  //     },
  //   },
  // ],
  // networks: [
  //   {
  //     name: "Diamante Mainnet",
  //     network: 0,
  //   },
  //   {
  //     name: "Binance Mainnet",
  //     network: 1,
  //   },
  //   {
  //     name: "Ethereum Mainnet",
  //     network: 2,
  //   },
  //   {
  //     name: "TRON Mainnet",
  //     network: 3,
  //   },
  // ],
};
